### ISSUE TITLE
[1.18.2] Connection to Create belts disconnects when chunk unloads.

### ISSUE THREAD

**Issue by TheUnderTaker11** [Technici4n/Modern-Dynamics#71] opened 2023-04-08 21:40 UTC
Title. Mod version =  Modern-Dynamics-0.2.6-beta.jar

Placing and re-breaking makes the connection work. Using an attractor on the belt block makes it visually connect, however no items will transfer.

Giving a block update also fixes the issue, as I placed a cobblestone block next to a non-working one and it immediately started working.

Before re-logging      
![image](https://user-images.githubusercontent.com/16872377/230743551-e36869f6-1dd5-4914-b0e9-d057700b8719.png)

after logging off and re-joining
![image](https://user-images.githubusercontent.com/16872377/230743584-bae0451d-8f22-495f-b441-0b2fdfbdffbb.png)

Yes, I know there is no extractor on it in my screenshots, that was just because I placed it to take these screenshots as proof.

**Comment by TheUnderTaker11** [comment] 2023-04-08 21:56
Just tested these pipes and the Modern Industrialization pipes side-by-side, and these pipes broke as usual but MI pipes worked without issue, if that helps.

**Comment by Technici4n** [comment] 2023-04-09 11:17
Does this also happen in 1.19?

**Comment by TheUnderTaker11** [comment] 2023-04-09 16:03
I don't know, my mod pack I'm playing is on 1.18.2.

**Comment by jpenilla** [comment] 2023-04-09 16:21
I can't reproduce on 1.19.2

**Comment by Technici4n** [comment] 2023-04-09 16:47
I believe this is a Create-Fabric "bug" (they need to send a block update) that was only fixed in 1.19. If they're still support 1.18, please report the issue to them.

**Closed by Technici4n** 2023-04-09 16:47 UTC
